services:
    CORS\Bundle\FriendlyCaptchaBundle\Validator\FriendlyCaptchaValidValidator:
        arguments:
            - '@http_client'
            - '%cors.friendly_captcha.secret%'
            - '%cors.friendly_captcha.sitekey%'
            - '%cors.friendly_captcha.endpoint.validation%'
        tags:
            - { name: validator.constraint_validator, alias: cors_friendly_captcha_validator }

    CORS\Bundle\FriendlyCaptchaBundle\Form\Type\FriendlyCaptchaType:
        arguments:
            - '%cors.friendly_captcha.sitekey%'
            - '%cors.friendly_captcha.use_local_script_files%'
            - '%cors.friendly_captcha.endpoint.puzzle%'
        tags:
            - { name: form.type }